---
name: "Build and Release"

on:
  push:
    branches:
      - "main"

jobs:
  build:
    name: "Build"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2
      - name: "Set up JDK 11"
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: "Cache Maven packages"
        uses: actions/cache@v2
        with:
          path: "~/.m2"
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: "Maven build"
        run: mvn clean install
      - uses: actions/upload-artifact@master
        with:
          name: jarfile
          path: target/TwitterScreenshotBot.jar

  release:
    needs: "build"
    name: "Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/download-artifact@master
        with:
          name: jarfile
          path: target/TwitterScreenshotBot.jar
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          draft: false
          title: "Development Build"
          files: |
            target/TwitterScreenshotBot.jar